name = "Sraffa"
uuid = "226d1a27-7d9b-44b1-8164-3dc284ddb16a"
authors = ["Johannes NÃ¤gele <johannes-naegele@web.de>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
julia = "1"
