name = "Sraffa"
uuid = "226d1a27-7d9b-44b1-8164-3dc284ddb16a"
authors = ["Johannes NÃ¤gele <johannes-naegele@web.de>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StrideArrays = "d1fa6d79-ef01-42a6-86c9-f7c551f8593b"

[compat]
julia = "1"
